export interface IndicatorDefinition {
  id: string;
  name: string;
  shortName: string;
  category: string;
  unit: string;
  frequency: string;
  source: string;
  sourceUrl: string;
  description: string;
  positiveDirection: string;
  color: string;
  lastUpdated: string;
  updateCadence: string;
  apiEndpoint?: string;
  apiParams?: Record<string, string>;
}

export const INDICATOR_DEFINITIONS: IndicatorDefinition[] = [
  {
    id: 'gdp_nominal',
    name: 'GDP (Nominal)',
    shortName: 'GDP',
    category: 'GDP',
    unit: '₦ Trillion',
    frequency: 'quarterly',
    source: 'NBS Nigeria',
    sourceUrl: 'https://www.nigerianstat.gov.ng',
    description: 'Nominal Gross Domestic Product at current basic prices',
    positiveDirection: 'up',
    lastUpdated: '2024-12-31',
    updateCadence: 'Quarterly (45-day lag)',
    color: '#22c55e',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/NY.GDP.MKTP.CD',
    apiParams: { format: 'json' }
  },
  {
    id: 'gdp_growth',
    name: 'GDP Growth Rate',
    shortName: 'GDP Growth',
    category: 'GDP',
    unit: '% YoY',
    frequency: 'quarterly',
    source: 'NBS Nigeria',
    sourceUrl: 'https://www.nigerianstat.gov.ng',
    description: 'Year-on-year real GDP growth rate',
    positiveDirection: 'up',
    lastUpdated: '2024-12-31',
    updateCadence: 'Quarterly (45-day lag)',
    color: '#16a34a',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/NY.GDP.MKTP.KD.ZG',
    apiParams: { format: 'json' }
  },
  {
    id: 'gdp_per_capita',
    name: 'GDP Per Capita',
    shortName: 'GDP/Capita',
    category: 'GDP',
    unit: 'USD',
    frequency: 'annual',
    source: 'World Bank',
    sourceUrl: 'https://data.worldbank.org',
    description: 'Gross national income per capita (current USD)',
    positiveDirection: 'up',
    lastUpdated: '2024-01-01',
    updateCadence: 'Annual',
    color: '#4ade80',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/NY.GNP.PCAP.CD',
    apiParams: { format: 'json' }
  },
  {
    id: 'inflation_headline',
    name: 'Headline Inflation (CPI)',
    shortName: 'Inflation',
    category: 'Inflation',
    unit: '% YoY',
    frequency: 'monthly',
    source: 'NBS Nigeria',
    sourceUrl: 'https://www.nigerianstat.gov.ng',
    description: 'Year-on-year change in Consumer Price Index',
    positiveDirection: 'down',
    lastUpdated: '2025-02-28',
    updateCadence: 'Monthly (mid-month lag)',
    color: '#ef4444',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/FP.CPI.TOTL.ZG',
    apiParams: { format: 'json' }
  },
  {
    id: 'inflation_food',
    name: 'Food Inflation',
    shortName: 'Food CPI',
    category: 'Inflation',
    unit: '% YoY',
    frequency: 'monthly',
    source: 'NBS Nigeria',
    sourceUrl: 'https://www.nigerianstat.gov.ng',
    description: 'Year-on-year change in food component of CPI',
    positiveDirection: 'down',
    lastUpdated: '2025-02-28',
    updateCadence: 'Monthly',
    color: '#f97316'
  },
  {
    id: 'inflation_core',
    name: 'Core Inflation',
    shortName: 'Core CPI',
    category: 'Inflation',
    unit: '% YoY',
    frequency: 'monthly',
    source: 'NBS Nigeria',
    sourceUrl: 'https://www.nigerianstat.gov.ng',
    description: 'Inflation excluding volatile food and energy prices',
    positiveDirection: 'down',
    lastUpdated: '2025-02-28',
    updateCadence: 'Monthly',
    color: '#fb923c'
  },
  {
    id: 'unemployment',
    name: 'Unemployment Rate',
    shortName: 'Unemployment',
    category: 'Labour',
    unit: '%',
    frequency: 'quarterly',
    source: 'NBS Nigeria',
    sourceUrl: 'https://www.nigerianstat.gov.ng',
    description: 'Percentage of labour force that is unemployed',
    positiveDirection: 'down',
    lastUpdated: '2024-09-30',
    updateCadence: 'Quarterly',
    color: '#a855f7',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/SL.UEM.TOTL.ZS',
    apiParams: { format: 'json' }
  },
  {
    id: 'fx_usd',
    name: 'NGN/USD Exchange Rate',
    shortName: 'USD/NGN',
    category: 'Exchange Rate',
    unit: '₦ per $',
    frequency: 'monthly',
    source: 'CBN Nigeria',
    sourceUrl: 'https://www.cbn.gov.ng',
    description: 'Official exchange rate of Naira against US Dollar',
    positiveDirection: 'down',
    lastUpdated: '2025-03-10',
    updateCadence: 'Daily (shown monthly avg)',
    color: '#3b82f6'
  },
  {
    id: 'fx_parallel',
    name: 'Parallel Market Rate',
    shortName: 'Parallel FX',
    category: 'Exchange Rate',
    unit: '₦ per $',
    frequency: 'monthly',
    source: 'Market / ABCON',
    sourceUrl: 'https://www.cbn.gov.ng',
    description: 'Unofficial parallel market exchange rate',
    positiveDirection: 'down',
    lastUpdated: '2025-03-10',
    updateCadence: 'Daily (shown monthly avg)',
    color: '#60a5fa'
  },
  {
    id: 'mpr',
    name: 'Monetary Policy Rate (MPR)',
    shortName: 'MPR',
    category: 'Interest Rates',
    unit: '%',
    frequency: 'monthly',
    source: 'CBN Nigeria',
    sourceUrl: 'https://www.cbn.gov.ng',
    description: 'Benchmark interest rate set by CBN MPC',
    positiveDirection: 'neutral',
    lastUpdated: '2025-02-28',
    updateCadence: 'Every 2 months (MPC meetings)',
    color: '#8b5cf6'
  },
  {
    id: 't_bill_91',
    name: '91-Day Treasury Bill Rate',
    shortName: 'T-Bill 91d',
    category: 'Interest Rates',
    unit: '%',
    frequency: 'monthly',
    source: 'CBN Nigeria / DMO',
    sourceUrl: 'https://www.dmo.gov.ng',
    description: 'Yield on 91-day Nigerian Government T-Bills',
    positiveDirection: 'neutral',
    lastUpdated: '2025-03-07',
    updateCadence: 'Weekly auction',
    color: '#7c3aed'
  },
  {
    id: 'exports',
    name: 'Total Exports',
    shortName: 'Exports',
    category: 'Trade',
    unit: '$ Billion',
    frequency: 'quarterly',
    source: 'NBS Nigeria',
    sourceUrl: 'https://www.nigerianstat.gov.ng',
    description: 'Total value of goods exported from Nigeria',
    positiveDirection: 'up',
    lastUpdated: '2024-09-30',
    updateCadence: 'Quarterly',
    color: '#06b6d4',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/NE.EXP.GNFS.ZS',
    apiParams: { format: 'json' }
  },
  {
    id: 'imports',
    name: 'Total Imports',
    shortName: 'Imports',
    category: 'Trade',
    unit: '$ Billion',
    frequency: 'quarterly',
    source: 'NBS Nigeria',
    sourceUrl: 'https://www.nigerianstat.gov.ng',
    description: 'Total value of goods imported into Nigeria',
    positiveDirection: 'neutral',
    lastUpdated: '2024-09-30',
    updateCadence: 'Quarterly',
    color: '#0891b2',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/NE.IMP.GNFS.ZS',
    apiParams: { format: 'json' }
  },
  {
    id: 'trade_balance',
    name: 'Trade Balance',
    shortName: 'Trade Bal.',
    category: 'Trade',
    unit: '$ Billion',
    frequency: 'quarterly',
    source: 'NBS Nigeria',
    sourceUrl: 'https://www.nigerianstat.gov.ng',
    description: 'Difference between exports and imports',
    positiveDirection: 'up',
    lastUpdated: '2024-09-30',
    updateCadence: 'Quarterly',
    color: '#22d3ee'
  },
  {
    id: 'govt_revenue',
    name: 'Government Revenue',
    shortName: 'Govt Revenue',
    category: 'Fiscal',
    unit: '₦ Trillion',
    frequency: 'quarterly',
    source: 'CBN / OAGF',
    sourceUrl: 'https://www.cbn.gov.ng',
    description: 'Federal government total revenue',
    positiveDirection: 'up',
    lastUpdated: '2024-09-30',
    updateCadence: 'Quarterly',
    color: '#f59e0b',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/GC.REV.XGRT.GD.ZS',
    apiParams: { format: 'json' }
  },
  {
    id: 'govt_expenditure',
    name: 'Government Expenditure',
    shortName: 'Govt Spend',
    category: 'Fiscal',
    unit: '₦ Trillion',
    frequency: 'quarterly',
    source: 'CBN / OAGF',
    sourceUrl: 'https://www.cbn.gov.ng',
    description: 'Federal government total expenditure',
    positiveDirection: 'neutral',
    lastUpdated: '2024-09-30',
    updateCadence: 'Quarterly',
    color: '#d97706',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/GC.XPN.TOTL.GD.ZS',
    apiParams: { format: 'json' }
  },
  {
    id: 'budget_balance',
    name: 'Budget Balance',
    shortName: 'Budget Bal.',
    category: 'Fiscal',
    unit: '₦ Trillion',
    frequency: 'annual',
    source: 'CBN / Budget Office',
    sourceUrl: 'https://www.budgetoffice.gov.ng',
    description: 'Federal government fiscal balance',
    positiveDirection: 'up',
    lastUpdated: '2024-12-31',
    updateCadence: 'Annual',
    color: '#b45309',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/GC.BAL.CASH.GD.ZS',
    apiParams: { format: 'json' }
  },
  {
    id: 'fx_reserves',
    name: 'Foreign Exchange Reserves',
    shortName: 'FX Reserves',
    category: 'External',
    unit: '$ Billion',
    frequency: 'monthly',
    source: 'CBN Nigeria',
    sourceUrl: 'https://www.cbn.gov.ng',
    description: 'Total foreign exchange reserves held by CBN',
    positiveDirection: 'up',
    lastUpdated: '2025-03-07',
    updateCadence: 'Weekly',
    color: '#14b8a6',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/FI.RES.TOTL.CD',
    apiParams: { format: 'json' }
  },
  {
    id: 'external_debt',
    name: 'External Debt',
    shortName: 'Ext. Debt',
    category: 'External',
    unit: '$ Billion',
    frequency: 'quarterly',
    source: 'DMO Nigeria',
    sourceUrl: 'https://www.dmo.gov.ng',
    description: 'Nigeria total external debt stock',
    positiveDirection: 'down',
    lastUpdated: '2024-09-30',
    updateCadence: 'Quarterly',
    color: '#0d9488',
    apiEndpoint: 'https://api.worldbank.org/v2/country/NGA/indicator/DT.DOD.DECT.CD',
    apiParams: { format: 'json' }
  },
  {
    id: 'oil_production',
    name: 'Crude Oil Production',
    shortName: 'Oil Output',
    category: 'Commodities',
    unit: 'mbpd',
    frequency: 'monthly',
    source: 'NNPC / OPEC',
    sourceUrl: 'https://www.nnpcgroup.com',
    description: 'Nigeria daily crude oil production',
    positiveDirection: 'up',
    lastUpdated: '2025-02-28',
    updateCadence: 'Monthly',
    color: '#64748b'
  },
  {
    id: 'oil_price',
    name: 'Brent Crude Price',
    shortName: 'Oil Price',
    category: 'Commodities',
    unit: '$/bbl',
    frequency: 'monthly',
    source: 'EIA / ICE',
    sourceUrl: 'https://www.eia.gov',
    description: 'Brent crude oil spot price',
    positiveDirection: 'up',
    lastUpdated: '2025-03-10',
    updateCadence: 'Daily (shown monthly avg)',
    color: '#475569'
  },
  {
    id: 'ngx_index',
    name: 'NGX All-Share Index',
    shortName: 'NGX ASI',
    category: 'Financial Markets',
    unit: 'Points',
    frequency: 'monthly',
    source: 'Nigerian Exchange Group',
    sourceUrl: 'https://ngxgroup.com',
    description: 'Nigerian Exchange All-Share Index',
    positiveDirection: 'up',
    lastUpdated: '2025-03-10',
    updateCadence: 'Daily (shown monthly close)',
    color: '#0ea5e9'
  },
  {
    id: 'market_cap',
    name: 'NGX Market Capitalisation',
    shortName: 'Mkt Cap',
    category: 'Financial Markets',
    unit: '₦ Trillion',
    frequency: 'monthly',
    source: 'Nigerian Exchange Group',
    sourceUrl: 'https://ngxgroup.com',
    description: 'Total market cap of all NGX listed equities',
    positiveDirection: 'up',
    lastUpdated: '2025-03-10',
    updateCadence: 'Daily (shown monthly close)',
    color: '#38bdf8'
  }
];

export const ECONOMIC_EVENTS = [
  { date: '2024-09-24', title: 'CBN Raises MPR to 27.25%', description: 'Monetary Policy Committee increased MPR by 50 basis points', category: 'monetary' },
  { date: '2024-06-25', title: 'CBN Holds MPR at 26.75%', description: 'MPC maintains rate amidst inflation concerns', category: 'monetary' },
  { date: '2024-03-26', title: 'CBN Hikes MPR to 26.75%', description: '100 basis point hike to combat inflation', category: 'monetary' },
  { date: '2024-01-30', title: 'Petrol Subsidy Removed', description: 'Federal government removes petrol subsidy', category: 'fiscal' },
  { date: '2023-07-25', title: 'CBN Raises MPR to 20.5%', description: 'Aggressive rate hike to stabilize naira', category: 'monetary' },
  { date: '2023-06-15', title: 'Naira Float Announced', description: 'CBN allows naira to float freely', category: 'external' },
];
